### ISSUE TITLE
Re implementation

### ISSUE THREAD

**Issue by kkonevets** [appaquet/extsort-rs#5]
Inspired by your code I have rewritten it and made some improvements:
1) code is much simpler and shorter
2) parallel sorting is used
3) efficient merging algorithm is applied
4) total speed is boosted, check it out

This is all it takes to re-implement your library:

```rust
use itertools::{Itertools, KMerge};
use rayon::prelude::*;
use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Result, Write};
use std::marker::PhantomData;
use std::path::{Path, PathBuf};

pub trait Sortable: Eq + Ord + Sized + Send + Sync {
    fn encode<W: Write>(&self, writer: &mut W);
    fn decode<R: Read>(reader: &mut R) -> Option<Self>;
}

pub struct ExternalSorter {
    max_mem: usize, // bytes
    tempdir: PathBuf,
    file_count: usize,
}

impl ExternalSorter {
    pub fn new(tempdir: PathBuf, max_mem: usize) -> ExternalSorter {
        assert!(max_mem > 0);
        ExternalSorter {
            max_mem, 
            tempdir,
            file_count: 0,
        }
    }

    fn file_name(&self, n: usize) -> PathBuf {
        self.tempdir.join(format!("{}", n))
    }

    fn write_chunk<T: Sortable>(&mut self, buf: &mut Vec<T>) -> Result<()> {
        buf.par_sort_unstable();
        let file = File::create(self.file_name(self.file_count))?;
        let mut out = BufWriter::new(file);
        for item in buf.iter() {
            item.encode(&mut out);
        }
        out.flush()?;
        self.file_count += 1;
        Ok(())
    }

    /// Sort a given iterator, returning a new iterator with items
    pub fn sort<T, I>(
        &mut self,
        iterator: I,
    ) -> Result<KMerge<<ChunkReader<T> as IntoIterator>::IntoIter>>
    where
        T: Sortable,
        I: Iterator<Item = T>,
    {
        let max_size = self.max_mem / std::mem::size_of::<T>() as usize;
        let mut buf = Vec::<T>::with_capacity(max_size);
        for item in iterator {
            if buf.len() == max_size {
                self.write_chunk(&mut buf)?;
                buf.clear();
            }
            buf.push(item);
        }
        if !buf.is_empty() {
            self.write_chunk(&mut buf)?;
        }
        std::mem::drop(buf);
        let mut readers = vec![];
        for n in 0..self.file_count {
            readers.push(ChunkReader::new(self.file_name(n))?);
        }
        Ok(readers.into_iter().kmerge())
    }
}

pub struct ChunkReader<T: Sortable> {
    reader: BufReader<std::fs::File>,
    phantom: PhantomData<T>,
}

impl<T: Sortable> ChunkReader<T> {
    pub fn new<P: AsRef<Path>>(fname: P) -> Result<ChunkReader<T>> {
        Ok(ChunkReader {
            reader: BufReader::new(File::open(fname)?),
            phantom: PhantomData,
        })
    }
}

impl<T: Sortable> Iterator for ChunkReader<T> {
    type Item = T;
    fn next(&mut self) -> Option<T> {
        T::decode(&mut self.reader)
    }
}
```

**Comment by appaquet** [comment]
Thanks for your contribution !

Could you provide some benchmark on how this implementation differs ? `cargo bench` before and after should give you that. 

But I think your implementation will be biased by the usage of `itertool` `kmerge`. If I read properly, their implementation, it loads all the items in a heap in memory: https://docs.rs/itertools/0.9.0/src/itertools/kmerge_impl.rs.html#176. If I'm correct, this defeats the purpose since external sorting is made for datasets that may not fit in memory. 

As a general rule, I'd like also like to minimize the usage of external crates for maintenance and compilation times. If it really benefits, `rayon` usage could be behind an optional feature.

**Comment by kkonevets** [comment]
No, `kmerge` does not use heap in the sense you mention, it does but only for top items in each list. I have tested in multiple times and no RAM consumption. So, don't worry.

`rayon` does really benefits, it gives approximately x4 time speed boost on my data. I have 200Gb binary file and only 50Gb of RAM.

**Comment by appaquet** [comment]
Read too quickly, I hadn't notice it was taking an iterator of iterator. I though the .into_iter() of your code were involving some flattening implementation of itertools to bring it back to a single iterator of items. 

Well, I'm definitely open to pull requests if you want to take a stab at it. Ideally in 2 PRs, one for the kmerge usage, one for rayon with benchmark before and after. I'd still put rayon behind a feature because of what it pulls. 

Thanks !

**Comment by kkonevets** [comment]
I would like to make a PR but am afraid have no time for that. All code is very simple and readable now. Just test my code and insert as is, maybe with some little modifications. That's it!

**Comment by appaquet** [comment]
We have all our own priorities ;) I'll let your issues open. Whoever gets to time first can implement it.

**Comment by Genarito** [comment]
It'd cool to not have to specify the `temp_dir`, wouldn't it be better to use [std::env::temp_dir](https://doc.rust-lang.org/std/env/fn.temp_dir.html)?

**Comment by Genarito** [comment]
I've made a [fork](https://github.com/Genarito/extsort-rs/tree/new-implementation) and applied this code and these are the results of benchmarking:

Old:

```
test tests::bench_ext_sort_1000     ... bench:       2,660 ns/iter (+/- 85)
test tests::bench_ext_sort_100_000  ... bench:   1,193,581 ns/iter (+/- 194,049)
test tests::bench_ext_sort_1million ... bench:   9,887,419 ns/iter (+/- 199,106)
test tests::bench_vec_sort_1000     ... bench:       1,849 ns/iter (+/- 47)
test tests::bench_vec_sort_100_000  ... bench:     179,514 ns/iter (+/- 4,603)
```

This implementation:

```
test tests::bench_ext_sort_1000     ... bench:     268,036 ns/iter (+/- 120,225)
test tests::bench_ext_sort_100_000  ... bench:   2,856,859 ns/iter (+/- 100,902)
test tests::bench_ext_sort_1million ... bench:  25,631,112 ns/iter (+/- 1,009,227)
test tests::bench_vec_sort_1000     ... bench:       1,843 ns/iter (+/- 93)
test tests::bench_vec_sort_100_000  ... bench:     178,694 ns/iter (+/- 3,146)
```

Maybe I'm missing something

**Comment by kkonevets** [comment]
Did not check it thoroughly, but first thing that comes to mind is that the 'old' implementation constructor takes number of items we can buffer in memory, while the 'new' takes number of bytes. So if you pass e.g. 100_000 to the new it will write much smaller chunks to disc then the old would do, resulting in speed fall. You have to adjust number of bytes to match to number of items in the old.

**Comment by kkonevets** [comment]
@Genarito by the way, take a look at [reimplementation in C++](https://github.com/kkonevets/gscounting/blob/master/include/externalsort.hpp), did not compare with Rust, but guess it will be faster.

**Comment by Genarito** [comment]
Cool! I'll try changing the number of bytes and let you know

**Comment by appaquet** [comment]
FYI, I just merged a cleanup PR in which the `Sortable` trait has been cleaned up closing #4 

As for benchmarks of this rewrite in comparison with my original implementation, it's probably not a fair comparison. I see a few things that could impact the benchmark results in the rewrite:

* Like @kkonevets  mentioned, my original implementation uses a max size in number of items, not in bytes. The reason it has been implemented like that is that I don't think we can always rely on the `size_of` the `Sortable` reliably. It would work with items that have no heap allocated fields (ex: struct with only primitives), but would fail to return a correct size with heap allocated fields (ex: struct contains a `Vec` or `String`). I prefer to let that judgment call to the user here. I could see providing a `set_max_size_bytes` with a proper warning in comment.

* My original implementation has a shortcut when the number of items you are sorting fits in the buffer size. In that case, I simply don't write and read anything from disk and the iterator is over the in-memory buffer.

* I haven't tested the impact of it, but I reuse file descriptors between the write and read stages (i.e. I don't re-open files once everything is written to disk).

In order to compare apples to apples, I implemented the 2 majors changes (itertools' kmerge & rayon parallel sort) from this PR on top of master. I also added an extra benchmark method to test a big number of items, but with a smaller buffer size in order to tests with a higher number of files. 

Here are the benchmark results:

### master
```
running 6 tests
test tests::bench_ext_sort_1000             ... bench:       1,808 ns/iter (+/- 6)
test tests::bench_ext_sort_100_000          ... bench:     824,656 ns/iter (+/- 23,981)
test tests::bench_ext_sort_1million_max100k ... bench:   6,779,024 ns/iter (+/- 36,301)
test tests::bench_ext_sort_1million_max1k   ... bench:  23,572,278 ns/iter (+/- 687,472)
test tests::bench_vec_sort_1000             ... bench:       1,012 ns/iter (+/- 6)
test tests::bench_vec_sort_100_000          ... bench:      99,954 ns/iter (+/- 498)
```

### [kmerge](https://github.com/appaquet/extsort-rs/compare/itertools-kmerge)
```
running 6 tests
test tests::bench_ext_sort_1000             ... bench:       1,799 ns/iter (+/- 12)
test tests::bench_ext_sort_100_000          ... bench:     875,384 ns/iter (+/- 17,274)
test tests::bench_ext_sort_1million_max100k ... bench:   7,088,664 ns/iter (+/- 59,447)
test tests::bench_ext_sort_1million_max1k   ... bench:  25,448,425 ns/iter (+/- 429,013)
test tests::bench_vec_sort_1000             ... bench:       1,013 ns/iter (+/- 24)
test tests::bench_vec_sort_100_000          ... bench:     100,117 ns/iter (+/- 2,116)
```

### [rayon](https://github.com/appaquet/extsort-rs/compare/rayon)
```
running 6 tests
test tests::bench_ext_sort_1000             ... bench:       1,788 ns/iter (+/- 6)
test tests::bench_ext_sort_100_000          ... bench:     827,278 ns/iter (+/- 13,886)
test tests::bench_ext_sort_1million_max100k ... bench:   6,854,260 ns/iter (+/- 51,252)
test tests::bench_ext_sort_1million_max1k   ... bench:  23,608,040 ns/iter (+/- 1,385,762)
test tests::bench_vec_sort_1000             ... bench:       1,242 ns/iter (+/- 3)
test tests::bench_vec_sort_100_000          ... bench:     122,058 ns/iter (+/- 446)
```

### [rayon + kmerge](https://github.com/appaquet/extsort-rs/compare/kmerge-and-rayon)
```
running 6 tests
test tests::bench_ext_sort_1000             ... bench:       1,912 ns/iter (+/- 32)
test tests::bench_ext_sort_100_000          ... bench:     895,551 ns/iter (+/- 20,433)
test tests::bench_ext_sort_1million_max100k ... bench:   7,415,775 ns/iter (+/- 239,190)
test tests::bench_ext_sort_1million_max1k   ... bench:  26,154,052 ns/iter (+/- 848,627)
test tests::bench_vec_sort_1000             ... bench:       1,023 ns/iter (+/- 7)
test tests::bench_vec_sort_100_000          ... bench:     100,210 ns/iter (+/- 410)
```

As we can see, Rayon and kmerge aren't that beneficial in the current benchmarks for some reasons. My assumptions:
* Rayon's threading extra complexity & overhead would probably only payoff if the buffer size is big enough for parallelism to have an impact
* kmerge's heap maintenance probably adds complexity over the simple approach the current implementation takes. Perhaps it would pay off in cases where the sorted data is skewed.

What do you guys think ?

**Comment by kkonevets** [comment]
Thanks for benching!
Yes, I wanted to mention that you have a `shortcut` to sort if needed memory is available. So, @Genarito don't forget about that when you will benchmark. You need to turn this optimization in master, implement it in the `new` code or just take an array that dos't fit in memory.
About file descriptors. Don't think that it really matters, cause you open and close a file only ones, at least I do so. That is quick.

It would be interesting to compare my little peace of code above with master when you switch of above mentioned `shortcut`. When I bench-marked on my data (I had 250 Gb file to sort) this little peace of code won significantly, as I mentioned at the beginning.

Overall I just wanted to simplify code and show that it can be rewritten in a simple way. Anyone can move on from this point. I call it `follow Occam's razor rule`

**Comment by appaquet** [comment]
@kkonevets It would be awesome if you could provide some benchmark on the branches I made against your data. Even better if you could provide data + code to bench.

In the meantime, I added new benchmarks that tests with random data, ordered data and reversed ordered data. It changes a bit the landscape, especially with Rayon with a enough data.

### master vs kmerge
```
 name                                           bench_master.txt ns/iter  bench_kmerge.txt ns/iter  diff ns/iter  diff %  speedup 
 tests::bench_ext_sort_1000_rand                19,833                    20,912                           1,079   5.44%   x 0.95 
 tests::bench_ext_sort_1000_rev                 1,918                     1,825                              -93  -4.85%   x 1.05 
 tests::bench_ext_sort_1000_sorted              1,689                     1,586                             -103  -6.10%   x 1.06 
 tests::bench_ext_sort_100_000_rand             2,883,692                 3,006,186                      122,494   4.25%   x 0.96 
 tests::bench_ext_sort_100_000_rev              835,540                   845,625                         10,085   1.21%   x 0.99 
 tests::bench_ext_sort_100_000_sorted           814,742                   812,332                         -2,410  -0.30%   x 1.00 
 tests::bench_ext_sort_1million_max100k_rand    29,285,416                30,429,667                   1,144,251   3.91%   x 0.96 
 tests::bench_ext_sort_1million_max100k_rev     6,958,592                 7,001,125                       42,533   0.61%   x 0.99 
 tests::bench_ext_sort_1million_max100k_sorted  6,703,117                 6,738,678                       35,561   0.53%   x 0.99 
 tests::bench_ext_sort_1million_max1k_rand      42,615,971                45,235,869                   2,619,898   6.15%   x 0.94 
 tests::bench_ext_sort_1million_max1k_rev       23,753,545                25,725,562                   1,972,017   8.30%   x 0.92 
 tests::bench_ext_sort_1million_max1k_sorted    23,649,077                25,082,901                   1,433,824   6.06%   x 0.94 
 tests::bench_ext_sort_1million_max500k_rand    30,717,794                31,773,776                   1,055,982   3.44%   x 0.97 
 tests::bench_ext_sort_1million_max500k_rev     6,898,520                 7,110,584                      212,064   3.07%   x 0.97 
 tests::bench_ext_sort_1million_max500k_sorted  6,640,775                 6,734,219                       93,444   1.41%   x 0.99 
 tests::bench_vec_sort_1000_rand                26,393                    26,003                            -390  -1.48%   x 1.01 
 tests::bench_vec_sort_1000_rev                 1,243                     1,263                               20   1.61%   x 0.98 
 tests::bench_vec_sort_1000_sorted              600                       587                                -13  -2.17%   x 1.02 
 tests::bench_vec_sort_100_000_rand             3,806,280                 3,756,686                      -49,594  -1.30%   x 1.01 
 tests::bench_vec_sort_100_000_rev              122,293                   123,216                            923   0.75%   x 0.99 
 tests::bench_vec_sort_100_000_sorted           52,556                    52,763                             207   0.39%   x 1.00 
```

# master vs rayon
```
 name                                           bench_master.txt ns/iter  bench_rayon.txt ns/iter  diff ns/iter   diff %  speedup 
 tests::bench_ext_sort_1000_rand                19,833                    20,137                            304    1.53%   x 0.98 
 tests::bench_ext_sort_1000_rev                 1,918                     1,808                            -110   -5.74%   x 1.06 
 tests::bench_ext_sort_1000_sorted              1,689                     1,586                            -103   -6.10%   x 1.06 
 tests::bench_ext_sort_100_000_rand             2,883,692                 2,430,602                    -453,090  -15.71%   x 1.19 
 tests::bench_ext_sort_100_000_rev              835,540                   866,825                        31,285    3.74%   x 0.96 
 tests::bench_ext_sort_100_000_sorted           814,742                   844,909                        30,167    3.70%   x 0.96 
 tests::bench_ext_sort_1million_max100k_rand    29,285,416                14,614,904                -14,670,512  -50.09%   x 2.00 
 tests::bench_ext_sort_1million_max100k_rev     6,958,592                 7,245,862                     287,270    4.13%   x 0.96 
 tests::bench_ext_sort_1million_max100k_sorted  6,703,117                 6,977,198                     274,081    4.09%   x 0.96 
 tests::bench_ext_sort_1million_max1k_rand      42,615,971                44,162,462                  1,546,491    3.63%   x 0.96 
 tests::bench_ext_sort_1million_max1k_rev       23,753,545                24,401,301                    647,756    2.73%   x 0.97 
 tests::bench_ext_sort_1million_max1k_sorted    23,649,077                24,230,553                    581,476    2.46%   x 0.98 
 tests::bench_ext_sort_1million_max500k_rand    30,717,794                13,511,363                -17,206,431  -56.01%   x 2.27 
 tests::bench_ext_sort_1million_max500k_rev     6,898,520                 7,119,827                     221,307    3.21%   x 0.97 
 tests::bench_ext_sort_1million_max500k_sorted  6,640,775                 6,860,364                     219,589    3.31%   x 0.97 
 tests::bench_vec_sort_1000_rand                26,393                    26,390                             -3   -0.01%   x 1.00 
 tests::bench_vec_sort_1000_rev                 1,243                     1,072                            -171  -13.76%   x 1.16 
 tests::bench_vec_sort_1000_sorted              600                       628                                28    4.67%   x 0.96 
 tests::bench_vec_sort_100_000_rand             3,806,280                 3,773,553                     -32,727   -0.86%   x 1.01 
 tests::bench_vec_sort_100_000_rev              122,293                   99,800                        -22,493  -18.39%   x 1.23 
 tests::bench_vec_sort_100_000_sorted           52,556                    52,432                           -124   -0.24%   x 1.00 
```

### master vs rayon+kmerge
```
 name                                           bench_master.txt ns/iter  bench_kmerge_rayon.txt ns/iter  diff ns/iter  diff %  speedup 
 tests::bench_ext_sort_1000_rand                19,833                    20,906                                 1,073   5.41%   x 0.95 
 tests::bench_ext_sort_1000_rev                 1,918                     1,831                                    -87  -4.54%   x 1.05 
 tests::bench_ext_sort_1000_sorted              1,689                     1,592                                    -97  -5.74%   x 1.06 
 tests::bench_ext_sort_100_000_rand             2,883,692                 3,030,365                            146,673   5.09%   x 0.95 
 tests::bench_ext_sort_100_000_rev              835,540                   853,699                               18,159   2.17%   x 0.98 
 tests::bench_ext_sort_100_000_sorted           814,742                   829,010                               14,268   1.75%   x 0.98 
 tests::bench_ext_sort_1million_max100k_rand    29,285,416                30,459,286                         1,173,870   4.01%   x 0.96 
 tests::bench_ext_sort_1million_max100k_rev     6,958,592                 7,028,579                             69,987   1.01%   x 0.99 
 tests::bench_ext_sort_1million_max100k_sorted  6,703,117                 6,759,031                             55,914   0.83%   x 0.99 
 tests::bench_ext_sort_1million_max1k_rand      42,615,971                45,243,177                         2,627,206   6.16%   x 0.94 
 tests::bench_ext_sort_1million_max1k_rev       23,753,545                25,626,714                         1,873,169   7.89%   x 0.93 
 tests::bench_ext_sort_1million_max1k_sorted    23,649,077                25,036,888                         1,387,811   5.87%   x 0.94 
 tests::bench_ext_sort_1million_max500k_rand    30,717,794                31,802,932                         1,085,138   3.53%   x 0.97 
 tests::bench_ext_sort_1million_max500k_rev     6,898,520                 6,942,943                             44,423   0.64%   x 0.99 
 tests::bench_ext_sort_1million_max500k_sorted  6,640,775                 6,676,130                             35,355   0.53%   x 0.99 
 tests::bench_vec_sort_1000_rand                26,393                    25,886                                  -507  -1.92%   x 1.02 
 tests::bench_vec_sort_1000_rev                 1,243                     1,276                                     33   2.65%   x 0.97 
 tests::bench_vec_sort_1000_sorted              600                       600                                        0   0.00%   x 1.00 
 tests::bench_vec_sort_100_000_rand             3,806,280                 3,746,032                            -60,248  -1.58%   x 1.02 
 tests::bench_vec_sort_100_000_rev              122,293                   122,055                                 -238  -0.19%   x 1.00 
 tests::bench_vec_sort_100_000_sorted           52,556                    52,485                                   -71  -0.14%   x 1.00 
```

As we can see, kmerge never wins. Rayon does improve with sufficient data like I expected. We can see a 2x improvement on enough data.

**Comment by kkonevets** [comment]
I don't get one thing. By `kmerge` you mean my peace of code or ,aster code where you use kmerge?

**Comment by appaquet** [comment]
See https://github.com/appaquet/extsort-rs/compare/itertools-kmerge

Essentially juste using itertools's kmerge instead of doing the basic loop on `next` that the current implementation has.

**Comment by kkonevets** [comment]
Got it. So as I said it would be interesting to compare my code with your's, not your's modified with your. See the difference? Actually it's not hard to do

**Comment by kkonevets** [comment]
I don't have the data I tested on. But it was a 250 binary array of items:
```rust
struct{
   x:u32,
   y:u32
}
```

**Comment by kkonevets** [comment]
About kmerge. At the end it's a standard priority queue. As I remember Rust has an implementation in std, you can try that one. But the point is the same - write less do more, don't reinvent a wheel

**Comment by kkonevets** [comment]
@appaquet [here](https://github.com/kkonevets/geo_detection/blob/9421a591123c380a1f232b6bff598cae8ff29a23/src/preprocessing.rs#L75) is how I used my ExtSorter 
I open a file steam to read 250Gb file, then pass the stream to ExtSorter, then save a result.

**Comment by Genarito** [comment]
Hi! I've been very busy and I couldn't try the new ideas. Is there any update on this? There are many forks, PRs and benchmarks that I don't know what is the current state of this crate, could you explain me how would be the roadmap to the new implementation, please? Maybe I could help

**Comment by appaquet** [comment]
Hi @Genarito,

This crate is supported and the current state is a working state. If your question is about performance, as my latest benchmark was showing, the only remaining item would be to allow the use of Rayon since it is beneficial when the buffer size is big enough for multithreading overhead to be offsetted. The use of `kmerge` was not beneficial, even if it simplifies the code. 

My plan is to bring support for parallel sorting of the in-memory buffer soon and release a new version. As for this simplified version, I won't change the code of the crate just for the sake of simplifying it if it doesn't bring any performance improvements and if it removes features.

I'm closing this issue in favour to the parallel sorting issue that was already open (#3).

If you have any other issues, feel free to open another issue.

**Comment by Genarito** [comment]
Cool! I'll be waiting! Thank you
